### ISSUE TITLE
Melhorias no TTS

### ISSUE THREAD

**Issue by MaikeMota** [marquesgabriel/bot-discord-comentarios-xvideos#1]
Melhorar o TTS e fazer a saída ser o seguitnte: 

Bot Disse:  Comentário do XVideo, em vez de citar que alguém comentou.

**Comment by marquesgabriel** [comment]
Muito bom, assim que ter uma janela para mexer eu arrumo e já atualizo!

**Comment by marquesgabriel** [comment]
Done
